## To configure your Mkdocs installation using this file,
## refer to Mkdocs documentation

# Basic site config
site_name: Web Handnotes
site_url: https://fost.github.io/web-handnotes
use_directory_urls: true

# Repository information
repo_url: https://github.com/fost/web-handnotes
repo_name: web-handnotes
edit_uri: edit/master/src

theme:
    name: material
    custom_dir: overrides
    palette:
        scheme: slate
        primary: amber
        accent: yellow
    font:
        text: Inter
        code: Roboto Mono
    language: ru
    features:
        - navigation.tabs
    shortcuts:
        search: 191

# Options
docs_dir: src

markdown_extensions:
    - meta
    - abbr
    - admonition
    - attr_list
    - def_list
    - pyembed.markdown
    - markdown.extensions.meta
    - md_in_html
    - pymdownx.details
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist
    - pymdownx.snippets:
          check_paths: true
          base_path: src

# Mkdocs Plugins
plugins:
    - search:
          lang:
              - ru
    - minify:
          minify_html: true


